name: Build image

on:
  workflow_dispatch:
  push:
    tags:        
      - '*'

jobs:
  call-build:
    uses: haridusministeerium/workflows/.github/workflows/docker-build-publish.yml@master
    secrets: inherit
    with:
      image: layr/postgres-cron

